version: '3'

services:
  app:
    build: .
    ports:
      - "8080:3000"
    links:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"

  proxy:
    image: steveltn/https-portal
    links:
      - app
    ports:
      - "80:80"
      - "443:443"
    environment:
      STAGE: 'local'
      DOMAINS: 'quotebook.local -> http://app:3000'
